# If this workflow is triggered by a push to master, it
#        deploys a SNAPSHOT
# If this workflow is triggered by publishing a Release, it
#        deploys a RELEASE with the selected version
#        updates the project version by incrementing the patch version
#        commits the version update change to the repository's default branch.
name: Deploy artifacts with Maven
on:
  push:
    branches: [master]
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Detect release type
      run: |-
        if [[ "${{github.event.ref}}" == "refs/heads/master" ]]; then
          echo "::set-output name=type::SNAPSHOT"
        else
          echo "::set-output name=type::RELEASE"
        fi
      id: release-detection
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Import Secrets
      uses: RichiCoder1/vault-action@v0.10.2
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        secrets: |
          common/jenkins/main NEXUS_GITHUB_ACTIONS_PSW | NEXUS_PSW;
          common/jenkins/main NEXUS_GITHUB_ACTIONS_USR | NEXUS_USR;
    - name: Set up Nexus authentication
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: camunda-nexus
        server-username: NEXUS_USR
        server-password: NEXUS_PSW
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - if: github.event.release
      name: Update version in pom.xml (Release only)
      run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
    - name: Run Maven (${{ steps.release-detection.outputs.type }})
      run: mvn -B clean install
    - name: Publish package (${{ steps.release-detection.outputs.type }})
      run: mvn -B deploy
    - name: Archive artifacts
      run: |-
        ZIPFILE=${{github.event.repository.name}}-${{github.event.release.tag_name}}.zip
        zip $ZIPFILE $(find target/nexus-staging -name "*.jar")
        echo "::set-output name=filename::${ZIPFILE}"
      id: zip
    - if: github.event.release
      name: Attach artifacts to GitHub Release (Release only)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.zip.outputs.filename }}
        asset_name: ${{ steps.zip.outputs.filename }}
        asset_content_type: application/zip
    - if: github.event.release
      name: Checkout ${{ github.event.repository.default_branch }} and commit new development version (Release only)
      run: |-
        git config --global user.name "Release Bot"
        git config --global user.email actions@github.com
        git fetch
        git checkout -b ${{ github.event.repository.default_branch }} --track origin/${{ github.event.repository.default_branch }}
        mvn -B org.apache.maven.plugins:maven-release-plugin:update-versions -DgenerateBackupPoms=false
        git add **pom.xml
        mvn -B scm:checkin -Dbasedir=. -Dmessage="release(v${{ github.event.release.tag_name }}): bump version" -DdeveloperConnectionUrl="scm:git:https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${{ github.event.repository.full_name }}.git"
